const urlAddresses = [
  "https://pokeapi.co/api/v2/pokemon/134/",
  "https://pokeapi.co/api/v2/pokemon/4/",
  "https://pokeapi.co/api/v2/pokemon/150/",
  "https://pokeapi.co/api/v2/pokemon/12/",
  "https://pokeapi.co/api/v2/pokemon/8/",
  "https://pokeapi.co/api/v2/pokemon/39/",
  "https://pokeapi.co/api/v2/pokemon/6/",
  "https://pokeapi.co/api/v2/pokemon/124/",
  "https://pokeapi.co/api/v2/pokemon/7/",
  "https://pokeapi.co/api/v2/pokemon/116/",
  "https://pokeapi.co/api/v2/pokemon/52/",
  "https://pokeapi.co/api/v2/pokemon/25/",
  "https://pokeapi.co/api/v2/pokemon/135/",
  "https://pokeapi.co/api/v2/pokemon/5/",
  "https://pokeapi.co/api/v2/pokemon/149/",
  "https://pokeapi.co/api/v2/pokemon/13/",
  "https://pokeapi.co/api/v2/pokemon/9/",
  "https://pokeapi.co/api/v2/pokemon/40/",
  "https://pokeapi.co/api/v2/pokemon/14/",
  "https://pokeapi.co/api/v2/pokemon/125/",
  "https://pokeapi.co/api/v2/pokemon/17/",
  "https://pokeapi.co/api/v2/pokemon/10/",
  "https://pokeapi.co/api/v2/pokemon/11/", 
  "https://pokeapi.co/api/v2/pokemon/136/", 
  "https://pokeapi.co/api/v2/pokemon/117/",
];

export { urlAddresses };
